### ISSUE TITLE
POS field does not exit. Update your file

### ISSUE THREAD

**Issue by jgarces02** [everestial/VCF-Simplify#3] opened 2018-10-18 17:44 UTC
Dear @everestial, 

First, first things... I love this script! Thanks a lot! Then, go to the problem: I've converted an initial VCF to table (and all worked perfectly) but in the inverse process (table to VCF) with this recently generated table I've got this problem: `POS field does not exit. Update your file`... I don't understand the reason, because this filed would be within the #CHROM line and it's specified this line mustn't be included.

My header would be this:
```
##fileformat=VCFv4.1
##source=VarScan2
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total depth of quality bases">
##INFO=<ID=SOMATIC,Number=0,Type=Flag,Description="Indicates if record is a somatic mutation">
##INFO=<ID=SS,Number=1,Type=String,Description="Somatic status of variant (0=Reference,1=Germline,2=Somatic,3=LOH, or 5=Unknown)">
##INFO=<ID=SSC,Number=1,Type=String,Description="Somatic score in Phred scale (0-255) derived from somatic p-value">
##INFO=<ID=GPV,Number=1,Type=Float,Description="Fisher's Exact Test P-value of tumor+normal versus no variant for Germline calls">
##INFO=<ID=SPV,Number=1,Type=Float,Description="Fisher's Exact Test P-value of tumor versus normal for Somatic/LOH calls">
##FILTER=<ID=str10,Description="Less than 10% or more than 90% of variant supporting reads on one strand">
##FILTER=<ID=indelError,Description="Likely artifact due to indel reads at this position">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
##FORMAT=<ID=RD,Number=1,Type=Integer,Description="Depth of reference-supporting bases (reads1)">
##FORMAT=<ID=AD,Number=1,Type=Integer,Description="Depth of variant-supporting bases (reads2)">
##FORMAT=<ID=FREQ,Number=1,Type=String,Description="Variant allele frequency">
##FORMAT=<ID=DP4,Number=1,Type=String,Description="Strand read counts: ref/fwd, ref/rev, var/fwd, var/rev">
```
Any idea, please? Thanks in advance!

**Comment by everestial** [comment] 2018-10-18 18:07
Thank you for using the tool. Could you share the complete error output? 
Additionally, it could be more helpful in debugging, if you could include a small file snippet both ways (VCF and TABLE).

**Comment by jgarces02** [comment] 2018-10-22 10:20
Of course, @everestial. 

This would be the VCF first lines, obtained through VarScan2:
```
##fileformat=VCFv4.1
##source=VarScan2
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total depth of quality bases">
##INFO=<ID=SOMATIC,Number=0,Type=Flag,Description="Indicates if record is a somatic mutation">
##(etc, etc, etc)
##FORMAT=<ID=FREQ,Number=1,Type=String,Description="Variant allele frequency">
##FORMAT=<ID=DP4,Number=1,Type=String,Description="Strand read counts: ref/fwd, ref/rev, var/fwd, var/rev">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	NORMAL	TUMOR
chr1	1594199	.	C	CT	.	PASS	DP=46;SS=1;SSC=4;GPV=6,0539E-19;SPV=3,2708E-1	GT:GQ:DP:RD:AD:FREQ:DP4	1/1:.:16:3:12:80%:2,1,8,4	1/1:.:30:3:26:89,66%:0,3,9,17
chr1	1647893	.	C	CTTTCTT	.	PASS	DP=76;SS=1;SSC=2;GPV=4,028E-8;SPV=5,915E-1	GT:GQ:DP:RD:AD:FREQ:DP4	0/1:.:59:42:17:28,81%:21,21,9,8	0/1:.:17:12:5:29,41%:3,9,3,2
chr1	3743433	.	T	TG	.	PASS	DP=22;SS=1;SSC=2;GPV=7,1052E-9;SPV=5,3493E-1	GT:GQ:DP:RD:AD:FREQ:DP4	1/1:.:14:3:11:78,57%:0,3,1,10	1/1:.:8:1:7:87,5%:1,0,0,7
chr1	6683565	.	GA	G	.	PASS	DP=19;SS=1;SSC=3;GPV=5,0106E-6;SPV=4,9381E-1	GT:GQ:DP:RD:AD:FREQ:DP4	0/1:.:11:4:7:63,64%:1,3,3,4	1/1:.:8:2:6:75%:2,0,3,3
chr1	7807966	.	GT	G	.	PASS	DP=19;SS=1;SSC=0;GPV=1,1285E-5;SPV=9,4005E-1	GT:GQ:DP:RD:AD:FREQ:DP4	1/1:.:10:2:8:80%:0,2,0,8	0/1:.:9:3:4:57,14%:2,1,0,4
chr1	7906859	.	T	TAAGA	.	PASS	DP=116;SS=1;SSC=3;GPV=5,6317E-21;SPV=4,1016E-1	GT:GQ:DP:RD:AD:FREQ:DP4	0/1:.:36:20:16:44,44%:10,10,10,6	0/1:.:80:41:39:48,75%:19,22,17,22
chr1	7907805	.	C	CT	.	PASS	DP=252;SS=1;SSC=15;GPV=1E0;SPV=2,8099E-2	GT:GQ:DP:RD:AD:FREQ:DP4	0/1:.:116:79:37:31,9%:45,34,18,19	0/1:.:136:75:60:44,44%:42,33,37,23
chr1	9034815	.	C	CAGA	.	PASS	DP=89;SS=1;SSC=2;GPV=2,28E-8;SPV=5,6398E-1	GT:GQ:DP:RD:AD:FREQ:DP4	0/1:.:58:43:15:25,86%:23,20,6,9	0/1:.:31:22:8:26,67%:11,11,3,5
chr1	9792105	.	G	GA	.	PASS	DP=20;SS=1;SSC=10;GPV=7,2653E-5;SPV=7,99E-2	GT:GQ:DP:RD:AD:FREQ:DP4	0/1:.:11:7:4:36,36%:1,6,1,3	1/1:.:9:2:7:77,78%:0,2,0,7
chr1	11086097	.	A	AT	.	PASS	DP=78;SS=1;SSC=24;GPV=1E0;SPV=3,8064E-3	GT:GQ:DP:RD:AD:FREQ:DP4	0/1:.:34:25:9:26,47%:9,16,1,8	0/1:.:44:18:26:59,09%:7,11,9,17
chr1	11347155	.	C	CTGTT	.	PASS	DP=62;SS=1;SSC=1;GPV=1,5316E-7;SPV=6,5299E-1	GT:GQ:DP:RD:AD:FREQ:DP4	0/1:.:46:31:15:32,61%:15,16,11,4	0/1:.:16:11:5:31,25%:4,7,2,3
chr1	11886383	.	C	CTG	.	PASS	DP=34;SS=1;SSC=3;GPV=5,1914E-7;SPV=5E-1	GT:GQ:DP:RD:AD:FREQ:DP4	0/1:.:13:7:6:46,15%:0,7,2,4	0/1:.:21:10:11:52,38%:2,8,0,11
```
This is the table output for your (amazing) script:
```
CHROM	POS	ID	REF	ALT	QUAL	FILTER	DP	SOMATIC	SS	SSC	GPV	SPV	NORMAL:GT	NORMAL:GQ	NORMAL:DP	NORMAL:RD	NORMAL:AD	NORMAL:FREQ	NORMAL:DP4	TUMOR:GT	TUMOR:GQ	TUMOR:DP	TUMOR:RD	TUMOR:AD	TUMOR:FREQ	TUMOR:DP4
chr1	1594199	.	C	CT	.	PASS	46	None	1	4	6.0,0.0	3.0,270.8	1/1	.	16	3	12	80%	2,1,8,4	1/1	.	30	3	26	89,66%	0,3,9,17
chr1	1647893	.	C	CTTTCTT	.	PASS	76	None	1	2	4.0,0.0	5.0,91.5	0/1	.	59	42	17	28,81%	21,21,9,8	0/1	.17	12	5	29,41%	3,9,3,2
chr1	3743433	.	T	TG	.	PASS	22	None	1	2	7.0,0.0	5.0,349.3	1/1	.	14	3	11	78,57%	0,3,1,10	1/1	.8	1	7	87,5%	1,0,0,7
chr1	6683565	.	GA	G	.	PASS	19	None	1	3	5.0,0.0	4.0,938.1	0/1	.	11	4	7	63,64%	1,3,3,4	1/1	.	82	6	75%	2,0,3,3
chr1	7807966	.	GT	G	.	PASS	19	None	1	0	1.0,0.013	9.0,400.5	1/1	.	10	2	8	80%	0,2,0,8	0/1	.9	3	4	57,14%	2,1,0,4
chr1	7906859	.	T	TAAGA	.	PASS	116	None	1	3	5.0,0.0	4.0,101.6	0/1	.	36	20	16	44,44%	10,10,10,6	0/1	.80	41	39	48,75%	19,22,17,22
chr1	7907805	.	C	CT	.	PASS	252	None	1	15	1.0	2.0,80.99	0/1	.	116	79	37	31,9%	45,34,18,19	0/1	.136	75	60	44,44%	42,33,37,23
chr1	9034815	.	C	CAGA	.	PASS	89	None	1	2	2.0,0.0	5.0,639.8	0/1	.	58	43	15	25,86%	23,20,6,9	0/1	.31	22	8	26,67%	11,11,3,5
chr1	9792105	.	G	GA	.	PASS	20	None	1	10	7.0,0.027	7.0,0.99	0/1	.	11	7	4	36,36%	1,6,1,3	1/1	.9	2	7	77,78%	0,2,0,7
```
And it is in the re-conversion of this table to the original VCF when the mentioned error happens... 
```
Checking required modules
VCF-Simplify: A tool to convert VCF to TABLE and/or HAPLOTYPE file and vice-versa.

Task assignment : "BuildVCF"
  - Sub Task : Convert TABLE file to VCF
Converting TABLE to VCF
Reading TABLE file "simp_wide.vcf" to VCF file "simp_wide_toVCF.vcf"

Reading meta header from file "header.vcf"
POS field does not exit. Update your file
Elapsed time : "0.2653069496154785".
```
Final re-converted VCF seems normal, but this error makes me doubt...
```
##fileformat=VCFv4.1
##source=VarScan2
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total depth of quality bases">
##INFO=<ID=SOMATIC,Number=0,Type=Flag,Description="Indicates if record is a somatic mutation">
##INFO=<ID=SS,Number=1,Type=String,Description="Somatic status of variant (0=Reference,1=Germline,2=Somatic,3=LOH, or 5=Unknown)">
##INFO=<ID=SSC,Number=1,Type=String,Description="Somatic score in Phred scale (0-255) derived from somatic p-value">
##INFO=<ID=GPV,Number=1,Type=Float,Description="Fisher's Exact Test P-value of tumor+normal versus no variant for Germline calls">
##INFO=<ID=SPV,Number=1,Type=Float,Description="Fisher's Exact Test P-value of tumor versus normal for Somatic/LOH calls">
##FILTER=<ID=str10,Description="Less than 10% or more than 90% of variant supporting reads on one strand">
##FILTER=<ID=indelError,Description="Likely artifact due to indel reads at this position">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
##FORMAT=<ID=RD,Number=1,Type=Integer,Description="Depth of reference-supporting bases (reads1)">
##FORMAT=<ID=AD,Number=1,Type=Integer,Description="Depth of variant-supporting bases (reads2)">
##FORMAT=<ID=FREQ,Number=1,Type=String,Description="Variant allele frequency">
##FORMAT=<ID=DP4,Number=1,Type=String,Description="Strand read counts: ref/fwd, ref/rev, var/fwd, var/rev">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	TUMOR	NORMAL
chr1	1594199	.	C	CT	.	PASS	DP=46;SOMATIC=None;SS=1;SSC=4;GPV=6.0,0.0;SPV=3.0,270.8	GT:FREQ:AD:RD:DP:DP4:GQ	1/1:89,66%:26:3:30:0,3,9,17:.	1/1:80%:12:3:16:2,1,8,4:.
chr1	1647893	.	C	CTTTCTT	.	PASS	DP=76;SOMATIC=None;SS=1;SSC=2;GPV=4.0,0.0;SPV=5.0,91.5	GT:FREQ:AD:RD:DP:DP4:GQ	0/1:29,41%:5:12:17:3,9,3,2:.	0/1:28,81%:17:42:59:21,21,9,8:.
chr1	3743433	.	T	TG	.	PASS	DP=22;SOMATIC=None;SS=1;SSC=2;GPV=7.0,0.0;SPV=5.0,349.3	GT:FREQ:AD:RD:DP:DP4:GQ	1/1:87,5%:7:1:8:1,0,0,7:.	1/1:78,57%:11:3:14:0,3,1,10:.
chr1	6683565	.	GA	G	.	PASS	DP=19;SOMATIC=None;SS=1;SSC=3;GPV=5.0,0.0;SPV=4.0,938.1	GT:FREQ:AD:RD:DP:DP4:GQ	1/1:75%:6:2:8:2,0,3,3:.	0/1:63,64%:7:4:11:1,3,3,4:.
chr1	7807966	.	GT	G	.	PASS	DP=19;SOMATIC=None;SS=1;SSC=0;GPV=1.0,0.013;SPV=9.0,400.5	GT:FREQ:AD:RD:DP:DP4:GQ	0/1:57,14%:4:3:9:2,1,0,4:.	1/1:80%:8:2:10:0,2,0,8:.
chr1	7906859	.	T	TAAGA	.	PASS	DP=116;SOMATIC=None;SS=1;SSC=3;GPV=5.0,0.0;SPV=4.0,101.6	GT:FREQ:AD:RD:DP:DP4:GQ	0/1:48,75%:39:41:80:19,22,17,22:.	0/1:44,44%:16:20:36:10,10,10,6:.
chr1	7907805	.	C	CT	.	PASS	DP=252;SOMATIC=None;SS=1;SSC=15;GPV=1.0;SPV=2.0,80.99	GT:FREQ:AD:RD:DP:DP4:GQ	0/1:44,44%:60:75:136:42,33,37,23:.	0/1:31,9%:37:79:116:45,34,18,19:.
```
Maybe there's no really a problem but it's only for get more convinced. Thanks again for your help!

**Comment by jgarces02** [comment] 2018-10-22 10:31
Of course, @everestial. 

This would be the VCF first lines, obtained through VarScan2:
```
##fileformat=VCFv4.1
##source=VarScan2
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total depth of quality bases">
##INFO=<ID=SOMATIC,Number=0,Type=Flag,Description="Indicates if record is a somatic mutation">
##(etc, etc, etc)
##FORMAT=<ID=FREQ,Number=1,Type=String,Description="Variant allele frequency">
##FORMAT=<ID=DP4,Number=1,Type=String,Description="Strand read counts: ref/fwd, ref/rev, var/fwd, var/rev">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	NORMAL	TUMOR
chr1	1594199	.	C	CT	.	PASS	DP=46;SS=1;SSC=4;GPV=6,0539E-19;SPV=3,2708E-1	GT:GQ:DP:RD:AD:FREQ:DP4	1/1:.:16:3:12:80%:2,1,8,4	1/1:.:30:3:26:89,66%:0,3,9,17
chr1	1647893	.	C	CTTTCTT	.	PASS	DP=76;SS=1;SSC=2;GPV=4,028E-8;SPV=5,915E-1	GT:GQ:DP:RD:AD:FREQ:DP4	0/1:.:59:42:17:28,81%:21,21,9,8	0/1:.:17:12:5:29,41%:3,9,3,2
chr1	3743433	.	T	TG	.	PASS	DP=22;SS=1;SSC=2;GPV=7,1052E-9;SPV=5,3493E-1	GT:GQ:DP:RD:AD:FREQ:DP4	1/1:.:14:3:11:78,57%:0,3,1,10	1/1:.:8:1:7:87,5%:1,0,0,7
chr1	6683565	.	GA	G	.	PASS	DP=19;SS=1;SSC=3;GPV=5,0106E-6;SPV=4,9381E-1	GT:GQ:DP:RD:AD:FREQ:DP4	0/1:.:11:4:7:63,64%:1,3,3,4	1/1:.:8:2:6:75%:2,0,3,3
chr1	7807966	.	GT	G	.	PASS	DP=19;SS=1;SSC=0;GPV=1,1285E-5;SPV=9,4005E-1	GT:GQ:DP:RD:AD:FREQ:DP4	1/1:.:10:2:8:80%:0,2,0,8	0/1:.:9:3:4:57,14%:2,1,0,4
chr1	7906859	.	T	TAAGA	.	PASS	DP=116;SS=1;SSC=3;GPV=5,6317E-21;SPV=4,1016E-1	GT:GQ:DP:RD:AD:FREQ:DP4	0/1:.:36:20:16:44,44%:10,10,10,6	0/1:.:80:41:39:48,75%:19,22,17,22
chr1	7907805	.	C	CT	.	PASS	DP=252;SS=1;SSC=15;GPV=1E0;SPV=2,8099E-2	GT:GQ:DP:RD:AD:FREQ:DP4	0/1:.:116:79:37:31,9%:45,34,18,19	0/1:.:136:75:60:44,44%:42,33,37,23
chr1	9034815	.	C	CAGA	.	PASS	DP=89;SS=1;SSC=2;GPV=2,28E-8;SPV=5,6398E-1	GT:GQ:DP:RD:AD:FREQ:DP4	0/1:.:58:43:15:25,86%:23,20,6,9	0/1:.:31:22:8:26,67%:11,11,3,5
chr1	9792105	.	G	GA	.	PASS	DP=20;SS=1;SSC=10;GPV=7,2653E-5;SPV=7,99E-2	GT:GQ:DP:RD:AD:FREQ:DP4	0/1:.:11:7:4:36,36%:1,6,1,3	1/1:.:9:2:7:77,78%:0,2,0,7
chr1	11086097	.	A	AT	.	PASS	DP=78;SS=1;SSC=24;GPV=1E0;SPV=3,8064E-3	GT:GQ:DP:RD:AD:FREQ:DP4	0/1:.:34:25:9:26,47%:9,16,1,8	0/1:.:44:18:26:59,09%:7,11,9,17
chr1	11347155	.	C	CTGTT	.	PASS	DP=62;SS=1;SSC=1;GPV=1,5316E-7;SPV=6,5299E-1	GT:GQ:DP:RD:AD:FREQ:DP4	0/1:.:46:31:15:32,61%:15,16,11,4	0/1:.:16:11:5:31,25%:4,7,2,3
chr1	11886383	.	C	CTG	.	PASS	DP=34;SS=1;SSC=3;GPV=5,1914E-7;SPV=5E-1	GT:GQ:DP:RD:AD:FREQ:DP4	0/1:.:13:7:6:46,15%:0,7,2,4	0/1:.:21:10:11:52,38%:2,8,0,11
```
This is the table output for your (amazing) script:
```
CHROM	POS	ID	REF	ALT	QUAL	FILTER	DP	SOMATIC	SS	SSC	GPV	SPV	NORMAL:GT	NORMAL:GQ	NORMAL:DP	NORMAL:RD	NORMAL:AD	NORMAL:FREQ	NORMAL:DP4	TUMOR:GT	TUMOR:GQ	TUMOR:DP	TUMOR:RD	TUMOR:AD	TUMOR:FREQ	TUMOR:DP4
chr1	1594199	.	C	CT	.	PASS	46	None	1	4	6.0,0.0	3.0,270.8	1/1	.	16	3	12	80%	2,1,8,4	1/1	.	30	3	26	89,66%	0,3,9,17
chr1	1647893	.	C	CTTTCTT	.	PASS	76	None	1	2	4.0,0.0	5.0,91.5	0/1	.	59	42	17	28,81%	21,21,9,8	0/1	.17	12	5	29,41%	3,9,3,2
chr1	3743433	.	T	TG	.	PASS	22	None	1	2	7.0,0.0	5.0,349.3	1/1	.	14	3	11	78,57%	0,3,1,10	1/1	.8	1	7	87,5%	1,0,0,7
chr1	6683565	.	GA	G	.	PASS	19	None	1	3	5.0,0.0	4.0,938.1	0/1	.	11	4	7	63,64%	1,3,3,4	1/1	.	82	6	75%	2,0,3,3
chr1	7807966	.	GT	G	.	PASS	19	None	1	0	1.0,0.013	9.0,400.5	1/1	.	10	2	8	80%	0,2,0,8	0/1	.9	3	4	57,14%	2,1,0,4
chr1	7906859	.	T	TAAGA	.	PASS	116	None	1	3	5.0,0.0	4.0,101.6	0/1	.	36	20	16	44,44%	10,10,10,6	0/1	.80	41	39	48,75%	19,22,17,22
chr1	7907805	.	C	CT	.	PASS	252	None	1	15	1.0	2.0,80.99	0/1	.	116	79	37	31,9%	45,34,18,19	0/1	.136	75	60	44,44%	42,33,37,23
chr1	9034815	.	C	CAGA	.	PASS	89	None	1	2	2.0,0.0	5.0,639.8	0/1	.	58	43	15	25,86%	23,20,6,9	0/1	.31	22	8	26,67%	11,11,3,5
chr1	9792105	.	G	GA	.	PASS	20	None	1	10	7.0,0.027	7.0,0.99	0/1	.	11	7	4	36,36%	1,6,1,3	1/1	.9	2	7	77,78%	0,2,0,7
```
And it is in the re-conversion of this table to the original VCF when the mentioned error happens... 
```
Checking required modules
VCF-Simplify: A tool to convert VCF to TABLE and/or HAPLOTYPE file and vice-versa.

Task assignment : "BuildVCF"
  - Sub Task : Convert TABLE file to VCF
Converting TABLE to VCF
Reading TABLE file "simp_wide.vcf" to VCF file "simp_wide_toVCF.vcf"

Reading meta header from file "header.vcf"
POS field does not exit. Update your file
Elapsed time : "0.2653069496154785".
```
Final re-converted VCF seems normal, but this error makes me doubt...
```
##fileformat=VCFv4.1
##source=VarScan2
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total depth of quality bases">
##INFO=<ID=SOMATIC,Number=0,Type=Flag,Description="Indicates if record is a somatic mutation">
##INFO=<ID=SS,Number=1,Type=String,Description="Somatic status of variant (0=Reference,1=Germline,2=Somatic,3=LOH, or 5=Unknown)">
##INFO=<ID=SSC,Number=1,Type=String,Description="Somatic score in Phred scale (0-255) derived from somatic p-value">
##INFO=<ID=GPV,Number=1,Type=Float,Description="Fisher's Exact Test P-value of tumor+normal versus no variant for Germline calls">
##INFO=<ID=SPV,Number=1,Type=Float,Description="Fisher's Exact Test P-value of tumor versus normal for Somatic/LOH calls">
##FILTER=<ID=str10,Description="Less than 10% or more than 90% of variant supporting reads on one strand">
##FILTER=<ID=indelError,Description="Likely artifact due to indel reads at this position">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
##FORMAT=<ID=RD,Number=1,Type=Integer,Description="Depth of reference-supporting bases (reads1)">
##FORMAT=<ID=AD,Number=1,Type=Integer,Description="Depth of variant-supporting bases (reads2)">
##FORMAT=<ID=FREQ,Number=1,Type=String,Description="Variant allele frequency">
##FORMAT=<ID=DP4,Number=1,Type=String,Description="Strand read counts: ref/fwd, ref/rev, var/fwd, var/rev">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	TUMOR	NORMAL
chr1	1594199	.	C	CT	.	PASS	DP=46;SOMATIC=None;SS=1;SSC=4;GPV=6.0,0.0;SPV=3.0,270.8	GT:FREQ:AD:RD:DP:DP4:GQ	1/1:89,66%:26:3:30:0,3,9,17:.	1/1:80%:12:3:16:2,1,8,4:.
chr1	1647893	.	C	CTTTCTT	.	PASS	DP=76;SOMATIC=None;SS=1;SSC=2;GPV=4.0,0.0;SPV=5.0,91.5	GT:FREQ:AD:RD:DP:DP4:GQ	0/1:29,41%:5:12:17:3,9,3,2:.	0/1:28,81%:17:42:59:21,21,9,8:.
chr1	3743433	.	T	TG	.	PASS	DP=22;SOMATIC=None;SS=1;SSC=2;GPV=7.0,0.0;SPV=5.0,349.3	GT:FREQ:AD:RD:DP:DP4:GQ	1/1:87,5%:7:1:8:1,0,0,7:.	1/1:78,57%:11:3:14:0,3,1,10:.
chr1	6683565	.	GA	G	.	PASS	DP=19;SOMATIC=None;SS=1;SSC=3;GPV=5.0,0.0;SPV=4.0,938.1	GT:FREQ:AD:RD:DP:DP4:GQ	1/1:75%:6:2:8:2,0,3,3:.	0/1:63,64%:7:4:11:1,3,3,4:.
chr1	7807966	.	GT	G	.	PASS	DP=19;SOMATIC=None;SS=1;SSC=0;GPV=1.0,0.013;SPV=9.0,400.5	GT:FREQ:AD:RD:DP:DP4:GQ	0/1:57,14%:4:3:9:2,1,0,4:.	1/1:80%:8:2:10:0,2,0,8:.
chr1	7906859	.	T	TAAGA	.	PASS	DP=116;SOMATIC=None;SS=1;SSC=3;GPV=5.0,0.0;SPV=4.0,101.6	GT:FREQ:AD:RD:DP:DP4:GQ	0/1:48,75%:39:41:80:19,22,17,22:.	0/1:44,44%:16:20:36:10,10,10,6:.
chr1	7907805	.	C	CT	.	PASS	DP=252;SOMATIC=None;SS=1;SSC=15;GPV=1.0;SPV=2.0,80.99	GT:FREQ:AD:RD:DP:DP4:GQ	0/1:44,44%:60:75:136:42,33,37,23:.	0/1:31,9%:37:79:116:45,34,18,19:.
```
I've check the original and re-converted VCF and the number of lines changes drastically (from 50856 to 4695)... any idea?

Thanks again for your help!

**Comment by everestial** [comment] 2018-10-22 19:28
@jgarces02 
I looked into the problem using the small data provided above, but it was not enough to produce the bug if there is any. 

<pre>$ python3 VCF-Simplify.py SimplifyVCF -inVCF testvcf.VCF -toType table -keepHeader yes -out testTable.txt

Checking required modules

Using option &quot;SimplifyVCF&quot;
Converting VCF To Table
[&apos;NORMAL&apos;, &apos;TUMOR&apos;]
- 2 samples found.

Writing the header to a separate output file.

## Extracting the following fields of interest:

  # SAMPLE of interest are: 
   [&apos;NORMAL&apos;, &apos;TUMOR&apos;]

  # INFO of interest are: 
   [&apos;DP&apos;, &apos;SOMATIC&apos;, &apos;SS&apos;, &apos;SSC&apos;, &apos;GPV&apos;, &apos;SPV&apos;]

  # FORMAT of interest are: 
   [&apos;GT&apos;, &apos;GQ&apos;, &apos;DP&apos;, &apos;RD&apos;, &apos;AD&apos;, &apos;FREQ&apos;, &apos;DP4&apos;]


- Output header of the simplified VCF file:
[&apos;CHROM&apos;, &apos;POS&apos;, &apos;ID&apos;, &apos;REF&apos;, &apos;ALT&apos;, &apos;QUAL&apos;, &apos;FILTER&apos;, &apos;DP&apos;, &apos;SOMATIC&apos;, &apos;SS&apos;, &apos;SSC&apos;, &apos;GPV&apos;, &apos;SPV&apos;, &apos;NORMAL:GT&apos;, &apos;NORMAL:GQ&apos;, &apos;NORMAL:DP&apos;, &apos;NORMAL:RD&apos;, &apos;NORMAL:AD&apos;, &apos;NORMAL:FREQ&apos;, &apos;NORMAL:DP4&apos;, &apos;TUMOR:GT&apos;, &apos;TUMOR:GQ&apos;, &apos;TUMOR:DP&apos;, &apos;TUMOR:RD&apos;, &apos;TUMOR:AD&apos;, &apos;TUMOR:FREQ&apos;, &apos;TUMOR:DP4&apos;]

Reading the input vcf file ... 

[W::vcf_parse] contig &apos;chr1&apos; is not defined in the header. (Quick workaround: index the file with tabix.)
Contig chr1 is being processed ... 

Elapsed time:  0.0036399364471435547
</pre>

<br>

<pre>$ python3 VCF-Simplify.py BuildVCF -fromType table -inFile testTable.txt -outVCF vcfReConvert.vcf -vcfHeader vcf_header.txt 

Checking required modules

Using option &quot;BuildVCF&quot;
Converting Table to VCF
converting Table file to VCF

Reading meta header from file &quot;vcf_header.txt&quot; 
Elapsed time : &quot;0.005556583404541016&quot;.
</pre>


It seems to me that the problem has to do with input file for (TABLE to VCF) and with the string matching being the issue somewhere. I think I can debug the problem at it's best if you can upload the actual file and the write the exact scripts that your are using for VCF to TABLE and again from TABLE to VCF. 

The changes in the number of lines has to do with the same error `POS field does not exit. Update your file`. As soon as the error is hit the program initially broke the loop and wrote the information it had already processed. 

I have now made some code changes 
  - replaced `break` with `sys.exit()` so that any error encounter will kill the program. 
  - other code changes in how header is processed. 

Please upload the input VCF. It is possible to upload actual file here in gzipped format, else you can share the file via dropbox or other method of your convenience.

Thanks,

**Comment by everestial** [comment] 2018-10-22 19:40
@jgarces02 
I just looked at the error `POS field does not exit. Update your file...`. This error message is being raised because `POS` field isn't finding a match in your intput `TABLE` file. 

Please share the exact VCF file, TABLE file and the scripts you are using both ways (vcf to table to vcf). 

Thanks for using the tool.

**Comment by jgarces02** [comment] 2018-10-23 08:55
Hi again, @everestial. Thanks for your time.

I've check the initial VCF and I've realized that was incorrectly generated: previous version of VarScan (2.3.9) separated all alternative alleles in the same position by a "/" instead of "," (according to VCF format specifications) and I guess that this [bug](https://sourceforge.net/p/varscan/discussion/1073559/thread/7f070311/) was the responsible of crashing your code. I've run again the new version of VarScan and it seems that the error disappears and the number of rows is kept...
```
chr1	19581442	.	G	GAA/A	.	PASS	DP=18;SS=5;SSC=0;GPV=1E0;SPV=6,6154E-1GT:GQ:DP:RD:AD:FREQ:DP4	0/1:.:9:6:2:25%:2,4,0,2	0/1:.:9:5:2:28,57%:1,4,0,2
chr1	38332057	.	T	TTC/-TCTC	.	PASS	DP=25;SS=5;SSC=0;GPV=1E0;SPV=6,1988E-1	GT:GQ:DP:RD:AD:FREQ:DP4	0/1:.:15:11:3:21,43%:11,0,3,0	0/1:.:10:6:2:25%:6,0,2,0
chr2	159027686	.	C	CA/T	.	PASS	DP=30;SS=5;SSC=0;GPV=1E0;SPV=9,5253E-1GT:GQ:DP:RD:AD:FREQ:DP4	0/1:.:8:2:3:60%:2,0,2,1	0/1:.:22:11:5:31,25%:8,3,3,2
```
Anyway, found [attached](https://github.com/everestial/VCF-Simplify/files/2505303/issue.zip) original files you asked. Thanks again!

*EDIT*: No, sorry, the problem persists. In the conversion VCF-table there're no problems, but it re-appears in the conversion table-VCF (with the previously transformed VCF). And I forgotten to add the header I used for the table-VCF conversion:
```
##fileformat=VCFv4.1
##source=VarScan2
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total depth of quality bases">
##INFO=<ID=SOMATIC,Number=0,Type=Flag,Description="Indicates if record is a somatic mutation">
##INFO=<ID=SS,Number=1,Type=String,Description="Somatic status of variant (0=Reference,1=Germline,2=Somatic,3=LOH, or 5=Unknown)">
##INFO=<ID=SSC,Number=1,Type=String,Description="Somatic score in Phred scale (0-255) derived from somatic p-value">
##INFO=<ID=GPV,Number=1,Type=Float,Description="Fisher's Exact Test P-value of tumor+normal versus no variant for Germline calls">
##INFO=<ID=SPV,Number=1,Type=Float,Description="Fisher's Exact Test P-value of tumor versus normal for Somatic/LOH calls">
##FILTER=<ID=str10,Description="Less than 10% or more than 90% of variant supporting reads on one strand">
##FILTER=<ID=indelError,Description="Likely artifact due to indel reads at this position">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
##FORMAT=<ID=RD,Number=1,Type=Integer,Description="Depth of reference-supporting bases (reads1)">
##FORMAT=<ID=AD,Number=1,Type=Integer,Description="Depth of variant-supporting bases (reads2)">
##FORMAT=<ID=FREQ,Number=1,Type=String,Description="Variant allele frequency">
##FORMAT=<ID=DP4,Number=1,Type=String,Description="Strand read counts: ref/fwd, ref/rev, var/fwd, var/rev">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	NORMAL	TUMOR
```

**Comment by everestial** [comment] 2018-11-05 03:06
Hi @jgarces02 
I am glad that you really liked this tool and are using it. I have made few changes and would appreciate any feedbacks you can provide to make it a more better tool.

Additionally, I was looking if you or someone else could provide some opinion on this haplotype phasing tool
https://github.com/everestial/phase-Extender I haven’t release this yet, there is some more makeup to be added and documentation to be improved. But, any feedback would be definitely helpful. Thanks !

**Comment by everestial** [comment] 2018-11-13 03:00
The issue is resolved. 
Closing.

**Closed as completed** 2018-11-13 02:59 UTC
